### ISSUE TITLE
Wallpapers should be added to .npmignore

### ISSUE THREAD

**Issue by Joery-M** [hejny/spacetrim#7]
Because of the images in the assets folder, 38.3MB is added to every download of this package.
There's just no need for this, especially since the images are [commented out in the readme](https://github.com/hejny/spacetrim/blob/d9adfbc20adfa8efa56f3dc543281eac5c40f736/README.md?plain=1#L22-L29), so they aren't even used anywhere

Also a lot of people wont trust a package that adds random unused files to its bundle

**Comment by hejny** [comment]
Thank you for reporting this issue, now in new patch version 72.3 kB
